version: '2'

services:

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: 'frontend'
    volumes:
      - ../../MessagingAppFrontend/messagingApp:/code
      - node_modules:/code/node_modules
    ports:
      - 4200:4200
    networks:
      - net

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: "backend"
    command: /app/mvnw spring-boot:run
    build: .
    working_dir: /app
    volumes:
      - ../../MessagingAppBackend:/app
      - m2:/root/.m2
    networks:
      - net

volumes:
  m2:
networks:
  net: